import { copyFile, mkdir, readdir, stat, writeFile } from "node:fs/promises";
import path from "node:path";

export async function prepareImportPackage({ input, output, dryRun = false }) {
  const inputDir = path.resolve(input);
  const outputDir = path.resolve(output);
  const pdfDir = path.join(outputDir, "pdf");

  const inputStats = await stat(inputDir);
  if (!inputStats.isDirectory()) {
    throw new Error(`Input is not a directory: ${inputDir}`);
  }

  const pdfFiles = await findPdfFiles(inputDir);
  const entries = pdfFiles.map((filePath, index) => {
    const fileName = makeNotebookLMFileName(filePath, index + 1);
    return {
      index: index + 1,
      sourcePath: filePath,
      fileName,
      relativeSourcePath: path.relative(inputDir, filePath),
      titleGuess: guessTitleFromFileName(filePath)
    };
  });

  if (!dryRun) {
    await mkdir(pdfDir, { recursive: true });

    for (const entry of entries) {
      await copyFile(entry.sourcePath, path.join(pdfDir, entry.fileName));
    }

    await writeFile(path.join(outputDir, "manifest.json"), `${JSON.stringify(entries, null, 2)}\n`, "utf8");
    await writeFile(path.join(outputDir, "manifest.csv"), toCsv(entries), "utf8");
    await writeFile(path.join(outputDir, "README.md"), makeReadme(entries), "utf8");
  }

  return {
    inputDir,
    outputDir,
    totalPdfCount: pdfFiles.length,
    preparedCount: entries.length,
    entries
  };
}

export async function findPdfFiles(dir) {
  const results = [];
  const items = await readdir(dir, { withFileTypes: true });

  for (const item of items) {
    const itemPath = path.join(dir, item.name);
    if (item.isDirectory()) {
      results.push(...await findPdfFiles(itemPath));
      continue;
    }
    if (item.isFile() && item.name.toLowerCase().endsWith(".pdf")) {
      results.push(itemPath);
    }
  }

  return results.sort((a, b) => a.localeCompare(b));
}

export function makeNotebookLMFileName(filePath, index) {
  const parsed = path.parse(filePath);
  const cleanedBase = parsed.name
    .normalize("NFKD")
    .replace(/[^\w\s.-]/g, "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 120) || `paper-${index}`;

  return `${String(index).padStart(4, "0")} - ${cleanedBase}.pdf`;
}

export function guessTitleFromFileName(filePath) {
  return path.parse(filePath).name
    .replace(/[_-]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function toCsv(entries) {
  const rows = [
    ["index", "fileName", "titleGuess", "relativeSourcePath"],
    ...entries.map((entry) => [
      entry.index,
      entry.fileName,
      entry.titleGuess,
      entry.relativeSourcePath
    ])
  ];

  return `${rows.map((row) => row.map(csvCell).join(",")).join("\n")}\n`;
}

function csvCell(value) {
  const text = String(value ?? "");
  return `"${text.replace(/"/g, '""')}"`;
}

function makeReadme(entries) {
  return `# NotebookLM Import Package

Generated by Zotero NotebookLM Bridge.

## Contents

- PDF files: ${entries.length}
- PDF directory: \`pdf/\`
- Machine-readable manifest: \`manifest.json\`
- Spreadsheet-friendly manifest: \`manifest.csv\`

## Next step

Upload the files in \`pdf/\` to NotebookLM manually, or use the future browser automation helper.
`;
}
